### DISCUSSION TITLE
Rule 'HostRegexp(`{host:.+}`)' no longer works in Traefik v3

### DISCUSSION THREAD

**Discussion by ToshY** [tarampampam/error-pages#275] [Q&A] [answered]
Current [docs](https://github.com/tarampampam/error-pages/wiki/Traefik-(docker-compose)) denote the usage of the following rule:

```yaml
      # use as "fallback" for any NON-registered services (with priority below normal)
      traefik.http.routers.error-pages-router.rule: HostRegexp(`{host:.+}`)
```

This rule works fine if my domain `example.com` is not yet accessible/deployed when using Traefik `v2.11`, and it will properly show the `ghost` template. 

![image](https://github.com/tarampampam/error-pages/assets/31921460/6382c76e-0372-4638-9632-71b00c3f6003)

However when upgrading to Traefik `v3.0` (`v3.0.0-rc1` -> `v3.0.0-rc5`) it seems to no longer work and shows the default (traefik) 404 text:

![image](https://github.com/tarampampam/error-pages/assets/31921460/af4cbe30-a3c2-40b8-8686-a932dc77dc1e)

---

I've been looking at the Traefik [migration docs](https://doc.traefik.io/traefik/master/migration/v2-to-v3/#new-v3-syntax-notable-changes) and it denotes that `HostRegexp` now uses so-called "Go regexp syntax", which I don't understand what's really changed.

**Comment by ToshY** [comment, marked as answer]
After a bit of digging in the docs, I've found the following section regarding ["Rule syntax"](https://doc.traefik.io/traefik/master/routing/routers/#rulesyntax) which includes an example (luckily) with `HostRegexp`.

```yaml
## Dynamic configuration
http:
  routers:
    Router-v3:
      rule: HostRegexp(`[a-z]+\\.traefik\\.com`)
      ruleSyntax: v3
    Router-v2:
      rule: HostRegexp(`{subdomain:[a-z]+}.traefik.com`)
      ruleSyntax: v2
```

So after seeing that, I tried <code>HostRegexp(\`.+\`)</code> instead, and that works.
