### ISSUE TITLE
Authorization prompts

### ISSUE THREAD

**Issue by justmytwospence** [tarampampam/error-pages#17]
Some services (Syncthing in my case), have a popup authorization prompt rather than something on the page itself. I'm not familiar with what this authorization method is, but it's the same thing my router uses for its admin UI. When my error-pages range includes status code 401, error-pages intercepts and presents the unauthorized page, never giving the popup the chance to... pop up. Right now I've just set my range to 402-599 to avoid this, but I thought you should know in case there's something that can be done to fix it.

**Comment by tarampampam** [comment]
I can't fix this on the `error-pages` side :( Please, ask for the solution in the https://github.com/traefik/traefik repository

**Comment by frugan-dev** [comment]
Hi @tarampampam, I have a similar case where I use the basic authentication middleware for accessing the Traefik panel and also with other containers:

```yaml
labels:
      - traefik.http.middlewares.admin-auth.basicauth.users=${TRAEFIK_USERNAME}:${TRAEFIK_HASHED_PASSWORD}
```

When one clicks `cancel` at the login prompt the text message `401 Unauthorized` from Traefik appears, not the custom one from `error-pages`.
Is it possible to fix this?

I'm using Traefik `v3.0.1` and this is the part I use with `error-pages`:

```yaml
error-pages:
    container_name: error-pages
    image: tarampampam/error-pages:${ERROR_PAGES_TAG:-latest}
    depends_on:
      - traefik
    networks:
      - traefik-public
    environment:
      LISTEN_PORT: ${ERROR_PAGES_LISTEN_PORT}
      TEMPLATE_NAME: ${ERROR_PAGES_TEMPLATE_NAME}
      DEFAULT_ERROR_PAGE: ${ERROR_PAGES_DEFAULT_ERROR_PAGE}
      DEFAULT_HTTP_CODE: ${ERROR_PAGES_DEFAULT_HTTP_CODE}
      SHOW_DETAILS: ${ERROR_PAGES_SHOW_DETAILS}
      DISABLE_L10N: ${ERROR_PAGES_DISABLE_L10N}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.middlewares.error-pages.errors.status=400-599
      - traefik.http.middlewares.error-pages.errors.service=service-error-pages
      - traefik.http.middlewares.error-pages.errors.query=/{status}.html

      - traefik.http.routers.router-error-pages-http.entrypoints=http
      - traefik.http.routers.router-error-pages-http.rule=HostRegexp(`.+`)
      - traefik.http.routers.router-error-pages-http.priority=1
      - traefik.http.routers.router-error-pages-http.middlewares=error-pages

      - traefik.http.routers.router-error-pages-https.entrypoints=https,entrypoint-forwardedHeaders-trustedIPs
      - traefik.http.routers.router-error-pages-https.rule=HostRegexp(`.+`)
      - traefik.http.routers.router-error-pages-https.priority=1
      - traefik.http.routers.router-error-pages-https.tls=true
      - traefik.http.routers.router-error-pages-https.middlewares=error-pages

      - traefik.http.services.service-error-pages.loadbalancer.server.port=${ERROR_PAGES_LISTEN_PORT}
```

P.S.
Among other things, I would like to point out that in `v3.x` of Traefik, if I'm not mistaken, they seem to have removed the named regex routers (e.g. `HostRegexp(``{host:.+}``)` becomes `HostRegexp(``.+``)`).
