### ISSUE TITLE
CPU spikes

### ISSUE THREAD

**Issue by averon420** [tarampampam/error-pages#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] And it has nothing to do with Traefik

### Describe the bug

I noticed cpu spikes on one of my VM machines, and figured with: `docker stats --format "table {{.Name}}t{{.CPUPerc}}t{{.MemUsage}}"` that like every 5-10 seconds **error-pages** the cpu usage spikes to 8-16% while my other containers chill at ~1%.

```
traefikt0.00%t24.01MiB / 1.929GiB
error-pagest17.05%t2.922MiB / 1.929GiB
adguardhomet0.02%t45.77MiB / 1.929GiB
portainert0.00%t8.27MiB / 1.929GiB
dozzlet0.00%t13.95MiB / 1.929GiB
sp_watchtowert0.02%t2.418MiB / 1.929GiB
apachet0.01%t5.945MiB / 1.929GiB
sp_traefikt0.01%t9.016MiB / 1.929GiB
autheliat0.00%t21.08MiB / 1.929GiB
sp_portainert0.01%t2.32MiB / 1.929GiB
whoamit0.00%t1MiB / 1.929GiB
traefik-bouncert0.00%t18.5MiB / 1.929GiB
```

honestly no idea why, I closed all http/s connections to the server and still had this issue.

### Configuration files

```yaml
error-pages:
    <<: *common-keys-alwaysup # See EXTENSION FIELDS at the top
    image: tarampampam/error-pages:2.20.0 # Using the latest tag is highly discouraged. Please, use tags in X.Y.Z format
    container_name: error-pages
    command:
      - "--log-level=error"      
      - "serve"
    networks:
      - traefik
    volumes:
      - ${APPDATA_DIR:?err}/error-pages/mytemplates:/opt/templates:ro # my templates
    environment:
      # TEMPLATE_PATH: /mytemplates/matrix.html
      TEMPLATE_NAME: matrix # set the error pages template
      SHOW_DETAILS: true
    labels:
      traefik.enable: true
      traefik.http.services.error-pages.loadbalancer.server.port: 8080
      com.centurylinklabs.watchtower.monitor-only: true
```

### Anything else?

maybe you can tell me, what could cause this

thanks a lot and I really like this project
