### ISSUE TITLE
For anything other than 404 in traefik

### ISSUE THREAD

**Issue by modem7** [tarampampam/error-pages#19]
More an FYI for others:

Just been doing some research and it seems that if you want to apply these to any container that *does* exist, you'll need to create new middleware in traefik. 

Easy enough by following:
https://dille.name/blog/2021/03/14/using-traefik-error-pages-to-handle-unavailable-services/

And applying the middleware to all your services. 

A good way to test the guide above:

``` yml
  httpbin: # A simple HTTP Request & Response Service.
    container_name: httpbin
    image: kennethreitz/httpbin
    restart: always
    networks:
      pihole:
        ipv4_address: 'static.ip.address.here'
    security_opt:
      - no-new-privileges:true
    labels: 
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.httpbin-rtr.entrypoints=https"
      - "traefik.http.routers.httpbin-rtr.rule=Host(`httpbin.$DOMAINNAME`)"
      - "traefik.http.routers.httpbin-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.httpbin-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.httpbin-rtr.middlewares=traefik-error-pages"
      ## HTTP Services
      - "traefik.http.routers.httpbin-rtr.service=httpbin-svc"
      - "traefik.http.services.httpbin-svc.loadbalancer.server.port=80"
```

https://www.modem7.com/books/docker/page/current-docker-compose — you can see how I've implemented multiple middlewares in each container.
