### ISSUE TITLE
Documented HostRegexp rule is broken for Traefik v3

### ISSUE THREAD

**Issue by theriverman** [tarampampam/error-pages#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] And it has nothing to do with Traefik

### Describe the bug

Hi,

The wiki needs to be updated based on the findings in this discussion: https://github.com/tarampampam/error-pages/discussions/275

Traefik v3 introduces some change to regex handling and the current wiki version of tarampampam/error-pages suggests an invalid configuration option.

### Steps to reproduce

Try using the official documentation with Traefik v3

### Configuration files

```yaml
# Wrong
traefik.http.routers.error-pages-router.rule: HostRegexp(`{host:.+}`)

# Good
traefik.http.routers.error-pages-router.rule: HostRegexp(`.+`)
```

### Relevant log output

```shell
N/A
```

### Anything else?

N/A
