### ISSUE TITLE
Middleware "error-pages-middleware@docker" does not exist

### ISSUE THREAD

**Issue by ToshY** [tarampampam/error-pages#40]
**Problem**
I'm currently setting up this container with the example provided in the README, but when looking at my Traefik logs, I see the following error log popping up when I up my containers.

```
{"entryPointName":"websecure","level":"error","msg":"middleware \"error-pages-middleware@docker\" does not exist","routerName":"maintenance-secure@docker","time":"2021-12-19T19:10:24+01:00"}
```

Maybe I'm missing something obvious, but I just can't seem to find it.

**Config**
`docker-compose.yml`
```yaml
# Custom error pages for downed containers
error-pages:
  image: tarampampam/error-pages:${ERROR_PAGES_VERSION}
  container_name: error-pages
  depends_on:
    - traefik
  environment:
    TEMPLATE_NAME: custom
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.error-pages-router.rule=HostRegexp(`{host:.+}`)"
    - "traefik.http.routers.error-pages-router.priority=10"
    - "traefik.http.routers.error-pages-router.tls=true"
    - "traefik.http.routers.error-pages-router.entrypoints=websecure"
    - "traefik.http.routers.error-pages-router.middlewares=error-pages-middleware@docker"
    - "traefik.http.services.error-pages-service.loadbalancer.server.port=8080"
    - "traefik.http.middlewares.error-pages-middleware.errors.status=400-599"
    - "traefik.http.middlewares.error-pages-middleware.errors.service=error-pages-service@docker"
    - "traefik.http.middlewares.error-pages-middleware.errors.query=/{status}.html"
    - "traefik.docker.network=proxy"
  networks:
    - proxy
  volumes:
    - /var/www/html/error-pages/error-pages.yml:/opt/error-pages.yml
    - /var/www/html/error-pages/custom.html:/opt/custom.html
    - /var/www/html/error-pages/custom:/opt/templates/custom

# Application maintenance page
maintenance:
  build:
    context: docker/apache
    args:
      APACHE_VERSION: ${APACHE_VERSION}
  container_name: maintenance_proxy
  depends_on:
    - error-pages
  security_opt:
    - no-new-privileges:true
  restart: 'no'
  volumes:
    - /var/www/html/error-pages/custom/503.2.html:/usr/local/apache2/htdocs/index.html:ro
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.maintenance-secure.entrypoints=websecure"
    - "traefik.http.routers.maintenance-secure.rule=Host(`${APP_DOMAIN}`, `www.${APP_DOMAIN}`)"
    - "traefik.http.routers.maintenance-secure.service=maintenance-service"
    - "traefik.http.routers.maintenance-secure.tls=true"
    - 'traefik.http.routers.maintenance-secure.middlewares=error-pages-middleware@docker'
    - "traefik.http.services.maintenance-service.loadbalancer.server.port=80"
    - "traefik.docker.network=proxy"
  networks:
    - proxy
```

`traefik.yml`
```yaml
api:
  dashboard: true

log:
  format: json
  level: ERROR

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: proxy
  file:
    directory: /dynamic
    watch: true
```

**Versions**
* error-pages: 2.0.0
* Traefik: 2.5
